---
name: CI
on:
    workflow_dispatch:
env:
    IMAGE_TAGS: ${{ github.sha }}
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}
jobs:
    build-server:
        name: Build go-fdo-server binaries
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: redhat-actions/buildah-build@v2
          with:
            image: go-fdo-server-builder
            tags: ${{ env.IMAGE_TAGS }}
            containerfiles: |
                Containerfile.builder
        - name: Push to github container registry
          id: push-to-registry
          uses: redhat-actions/push-to-registry@v2
          with:
            image: go-fdo-server-builder
            tags: ${{ env.IMAGE_TAGS }}
            registry: ${{ env.IMAGE_REGISTRY }}
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
            extra-args: |
              --disable-content-trust
        outputs:
          digest: ${{ steps.push-to-registry.outputs.digest }}

    build-manufacturing:
        name: Build manufacturing server container
        runs-on: ubuntu-latest
        needs: build-server
        steps:
        - uses: actions/checkout@v3
        - name: build image using buildah
          uses: redhat-actions/buildah-build@v2
          with:
            image: go-fdo-server-manufacturing
            tags: ${{ env.IMAGE_TAGS }}
            build-args: |
                BUILDER_DIGEST=${{ needs.build-server.outputs.digest }}
                PORT=8038
                DB_NAME="/data/mfg.db"
                DB_PASS="${{ secrets.DB_PASS }}"
            containerfiles: |
                Containerfile
        - name: push to registry
          uses: redhat-actions/push-to-registry@v2
          with:
            image: go-fdo-server-manufacturing
            tags: ${{ env.IMAGE_TAGS }}
            registry: ${{ env.IMAGE_REGISTRY }}
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
            extra-args: |
              --disable-content-trust

    build-rendezvous:
        name: Build rendezvous server container
        runs-on: ubuntu-latest
        needs: build-server
        steps:
        - uses: actions/checkout@v3
        - name: build image using buildah
          uses: redhat-actions/buildah-build@v2
          with:
            image: go-fdo-server-rendezvous
            tags: ${{ env.IMAGE_TAGS }}
            build-args: |
                PORT=8041
                DB_NAME="/data/rv.db"
                DB_PASS="${{ secrets.DB_PASS }}"
            containerfiles: |
                Containerfile
        - name: Push to registry
          uses: redhat-actions/push-to-registry@v2
          with:
            image: go-fdo-server-rendezvous
            tags: ${{ env.IMAGE_TAGS }}
            registry: ${{ env.IMAGE_REGISTRY }}
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
            extra-args: |
              --disable-content-trust  
    build-owner:
        name: Build owner server container
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: build image using buildah
          uses: redhat-actions/buildah-build@v2
          with:
            image: go-fdo-server-owner
            tags: ${{ env.IMAGE_TAGS }}
            build-args: |
                PORT=8043
                DB_NAME="/data/owner.db"
                DB_PASS="${{ secrets.DB_PASS }}"
            containerfiles: |
                Containerfile
        - name: Push to registry
          uses: redhat-actions/push-to-registry@v2
          with:
            image: go-fdo-server-owner
            tags: ${{ env.IMAGE_TAGS }}
            registry: ${{ env.IMAGE_REGISTRY }}
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
            extra-args: |
              --disable-content-trust